
import classes.ConnectionProvider;
import java.sql.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author color
 */
public class Add_Book extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Add_Book() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book_title_label_ = new javax.swing.JLabel();
        add_book_button_ = new javax.swing.JButton();
        back_button_ = new javax.swing.JButton();
        dtuName_label_ = new javax.swing.JLabel();
        author_name_label_ = new javax.swing.JLabel();
        author_name_field_ = new javax.swing.JTextField();
        published_year_label_ = new javax.swing.JLabel();
        published_year_field_ = new javax.swing.JTextField();
        book_category_label_ = new javax.swing.JLabel();
        book_title_field_ = new javax.swing.JTextField();
        book_category_field_ = new javax.swing.JComboBox<>();
        book_price_label_ = new javax.swing.JLabel();
        book_price_field_ = new javax.swing.JTextField();
        book_quantity_label_ = new javax.swing.JLabel();
        book_quantity_field_ = new javax.swing.JTextField();
        reset_button_ = new javax.swing.JButton();
        book_isbn_label_ = new javax.swing.JLabel();
        book_isbn_field_ = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        book_title_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_title_label_.setText("BOOK TITLE :");

        add_book_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add_book_button_.setText("ADD");
        add_book_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_book_button_ActionPerformed(evt);
            }
        });

        back_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_button_.setText("BACK");
        back_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_button_ActionPerformed(evt);
            }
        });

        dtuName_label_.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dtuName_label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dtuName_label_.setText("ADD BOOK");

        author_name_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        author_name_label_.setText("AUTHOR NAME :");

        author_name_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        published_year_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        published_year_label_.setText("PUBLISHED YEAR :");

        published_year_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        book_category_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_category_label_.setText("BOOK CATEGORY : ");

        book_title_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_title_field_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_title_field_ActionPerformed(evt);
            }
        });

        book_category_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_category_field_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERAL", "CIVIL ", "CHEMICAL", "ELECTRICAL", "MECHANICAL ", "ENVIRONMENT", "BIOTECHNOLOGY", "COMPUTER SCIENCE", "PRODUCTION & INDUSTRIAL", "INFORMATION TECHNOLOGY", "MATHEMATICS & COMPUTATION" }));
        book_category_field_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_category_field_ActionPerformed(evt);
            }
        });

        book_price_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_price_label_.setText("BOOK PRICE :");

        book_price_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        book_quantity_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_quantity_label_.setText("QUANTITY : ");

        book_quantity_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        reset_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset_button_.setText("RESET");
        reset_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_button_ActionPerformed(evt);
            }
        });

        book_isbn_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_isbn_label_.setText("BOOK ISBN :");

        book_isbn_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_isbn_field_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_isbn_field_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtuName_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book_title_label_)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(add_book_button_)
                            .addGap(25, 25, 25)
                            .addComponent(reset_button_)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(back_button_))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(book_quantity_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(book_price_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(book_category_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(published_year_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(author_name_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(book_title_field_)
                                .addComponent(author_name_field_)
                                .addComponent(published_year_field_)
                                .addComponent(book_category_field_, 0, 400, Short.MAX_VALUE)
                                .addComponent(book_price_field_)
                                .addComponent(book_quantity_field_))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(book_isbn_label_)
                        .addGap(113, 113, 113)
                        .addComponent(book_isbn_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(dtuName_label_)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_isbn_label_)
                    .addComponent(book_isbn_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_title_label_)
                    .addComponent(book_title_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author_name_label_)
                    .addComponent(author_name_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(published_year_label_)
                    .addComponent(published_year_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_category_label_)
                    .addComponent(book_category_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_price_label_)
                    .addComponent(book_price_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_quantity_label_)
                    .addComponent(book_quantity_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_button_)
                    .addComponent(add_book_button_)
                    .addComponent(reset_button_))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_book_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_book_button_ActionPerformed
        //Add Book and show conformation
        //Book ID is dynamically updated
        //Book location is always library as default
        String book_isbn = book_isbn_field_.getText();
        String book_title = book_title_field_.getText();
        String book_author = author_name_field_.getText();
        String published_year = published_year_field_.getText();
        String book_category = (String)book_category_field_.getSelectedItem();
        String book_price = book_price_field_.getText();
        String books_quantity = book_quantity_field_.getText();
        int count = Integer.parseInt(books_quantity);
        String all_book_ids = "";
        
        //adding multiple books of same time, will diff book ids
        for(int i=0;i<count;i++) {
            try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into books(BOOK_ISBN, BOOK_TITLE, AUTHOR_NAME, PUBLISHED_YEAR, BOOK_CATEGORY, BOOK_PRICE) values('"+book_isbn+"' , '"+book_title+"', '"+book_author+"', '"+published_year+"', '"+book_category+"','"+book_price+"')");
            ResultSet old_id = st.executeQuery("select last_insert_id()");      //fetch last added id
            old_id.next();
            String last_added_book_id = old_id.getString(1);
            all_book_ids = all_book_ids + last_added_book_id + " ";
            } catch(Exception err) {
            JOptionPane.showInternalMessageDialog(null, err);
            }
        }
        if(all_book_ids.length()==2) {          //Only 1 Book Added
           JOptionPane.showInternalConfirmDialog(null, "BOOK ADDED SUCCESSFULLY \nBOOK ID IS : " + all_book_ids, "BOOK ADDED",JOptionPane.PLAIN_MESSAGE);
            setVisible(false);
           new Add_Book().setVisible(true);        //Remove old text
        } else if(all_book_ids!="") {          //More than 1 book added
           JOptionPane.showInternalConfirmDialog(null, "BOOKS ADDED SUCCESSFULLY \nBOOK IDs ARE : " + all_book_ids, "BOOKS ADDED",JOptionPane.PLAIN_MESSAGE);
           setVisible(false); 
           new Add_Book().setVisible(true);        //Remove old text 
        } else {
            JOptionPane.showInternalMessageDialog(null, "PLEASE CHECK INPUT FIELDS");
        }
        
    }//GEN-LAST:event_add_book_button_ActionPerformed

    private void back_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_button_ActionPerformed
        // Open Admin Page
        setVisible(false);
        new Admin_Home_Page().setVisible(true); 
        
    }//GEN-LAST:event_back_button_ActionPerformed

    private void book_category_field_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_category_field_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_category_field_ActionPerformed

    private void book_title_field_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_title_field_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_title_field_ActionPerformed

    private void reset_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_button_ActionPerformed
        // Delete all data of text fields
        setVisible(false);
        new Add_Book().setVisible(true); 
    }//GEN-LAST:event_reset_button_ActionPerformed

    private void book_isbn_field_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_isbn_field_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_isbn_field_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_book_button_;
    private javax.swing.JTextField author_name_field_;
    private javax.swing.JLabel author_name_label_;
    private javax.swing.JButton back_button_;
    private javax.swing.JComboBox<String> book_category_field_;
    private javax.swing.JLabel book_category_label_;
    private javax.swing.JTextField book_isbn_field_;
    private javax.swing.JLabel book_isbn_label_;
    private javax.swing.JTextField book_price_field_;
    private javax.swing.JLabel book_price_label_;
    private javax.swing.JTextField book_quantity_field_;
    private javax.swing.JLabel book_quantity_label_;
    private javax.swing.JTextField book_title_field_;
    private javax.swing.JLabel book_title_label_;
    private javax.swing.JLabel dtuName_label_;
    private javax.swing.JTextField published_year_field_;
    private javax.swing.JLabel published_year_label_;
    private javax.swing.JButton reset_button_;
    // End of variables declaration//GEN-END:variables

}
