
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author color
 */
public class Admin_Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    public Admin_Home_Page() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_book_button_ = new javax.swing.JButton();
        delete_book_button_ = new javax.swing.JButton();
        issue_book_button_ = new javax.swing.JButton();
        returned_book_button_ = new javax.swing.JButton();
        add_student_button_ = new javax.swing.JButton();
        delete_student_button_ = new javax.swing.JButton();
        edit_student_button_ = new javax.swing.JButton();
        student_fine_button_ = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        close_button_ = new javax.swing.JButton();
        log_out_button_ = new javax.swing.JButton();
        admin_dashboard_label_ = new javax.swing.JLabel();
        powered_by_label_ = new javax.swing.JLabel();
        made_by_blackhatsanta_label_ = new javax.swing.JLabel();
        search_book_button_ = new javax.swing.JButton();
        students_list_button_ = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        add_book_button_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_book_button_.setText("ADD BOOK");
        add_book_button_.setPreferredSize(new java.awt.Dimension(225, 75));
        add_book_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_book_button_ActionPerformed(evt);
            }
        });

        delete_book_button_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete_book_button_.setText("DELETE BOOK");
        delete_book_button_.setPreferredSize(new java.awt.Dimension(225, 100));
        delete_book_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_book_button_ActionPerformed(evt);
            }
        });

        issue_book_button_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        issue_book_button_.setText("ISSUE BOOK");
        issue_book_button_.setPreferredSize(new java.awt.Dimension(225, 100));
        issue_book_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue_book_button_ActionPerformed(evt);
            }
        });

        returned_book_button_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        returned_book_button_.setText("RETURNED BOOK");
        returned_book_button_.setPreferredSize(new java.awt.Dimension(225, 100));
        returned_book_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returned_book_button_ActionPerformed(evt);
            }
        });

        add_student_button_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_student_button_.setText("ADD STUDENT");
        add_student_button_.setPreferredSize(new java.awt.Dimension(225, 100));
        add_student_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_student_button_ActionPerformed(evt);
            }
        });

        delete_student_button_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete_student_button_.setText("DELETE STUDENT");
        delete_student_button_.setPreferredSize(new java.awt.Dimension(225, 100));
        delete_student_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_student_button_ActionPerformed(evt);
            }
        });

        edit_student_button_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edit_student_button_.setText("EDIT STUDENT");
        edit_student_button_.setPreferredSize(new java.awt.Dimension(225, 100));
        edit_student_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_student_button_ActionPerformed(evt);
            }
        });

        student_fine_button_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        student_fine_button_.setText("STUDENT FINE");
        student_fine_button_.setPreferredSize(new java.awt.Dimension(225, 100));
        student_fine_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_fine_button_ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setText("jButton9");
        jButton9.setPreferredSize(new java.awt.Dimension(225, 100));

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton10.setText("jButton10");
        jButton10.setPreferredSize(new java.awt.Dimension(225, 100));

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton11.setText("jButton11");
        jButton11.setPreferredSize(new java.awt.Dimension(225, 100));

        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton12.setText("jButton12");
        jButton12.setPreferredSize(new java.awt.Dimension(225, 100));

        close_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close_button_.setText("CLOSE");
        close_button_.setPreferredSize(new java.awt.Dimension(100, 25));
        close_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_button_ActionPerformed(evt);
            }
        });

        log_out_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        log_out_button_.setText("LOG-OUT");
        log_out_button_.setPreferredSize(new java.awt.Dimension(100, 25));
        log_out_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_button_ActionPerformed(evt);
            }
        });

        admin_dashboard_label_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admin_dashboard_label_.setText("ADMIN DASHBOARD - DTU");

        powered_by_label_.setText("POWERED BY : JAVA / JSWING / MYSQL");

        made_by_blackhatsanta_label_.setText("MADE WITH LOVE IN INDIA BY @BLACKHATSANTA (ACCIOJOB BATCH 21)");

        search_book_button_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        search_book_button_.setText("SEARCH BOOK");
        search_book_button_.setPreferredSize(new java.awt.Dimension(190, 100));
        search_book_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_book_button_ActionPerformed(evt);
            }
        });

        students_list_button_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        students_list_button_.setText("STUDENTS LIST");
        students_list_button_.setPreferredSize(new java.awt.Dimension(190, 100));
        students_list_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                students_list_button_ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("jButton3");
        jButton3.setPreferredSize(new java.awt.Dimension(190, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(admin_dashboard_label_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(add_book_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(add_student_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(delete_book_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(delete_student_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(powered_by_label_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(made_by_blackhatsanta_label_, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(edit_student_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(issue_book_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(returned_book_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGap(75, 75, 75)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(search_book_button_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(student_fine_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(log_out_button_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addComponent(close_button_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(students_list_button_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(returned_book_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(issue_book_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(delete_book_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(add_book_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(search_book_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(add_student_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit_student_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(students_list_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(student_fine_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(delete_student_button_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(admin_dashboard_label_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(powered_by_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(made_by_blackhatsanta_label_)
                        .addContainerGap(131, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(close_button_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(log_out_button_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_button_ActionPerformed
        // Close the Program
        int a = JOptionPane.showInternalConfirmDialog(null, "DO YOU REALLY WANT TO EXIT", "SELECT", JOptionPane.YES_NO_OPTION);
        if(a==0) System.exit(0);        //Close the Program
    }//GEN-LAST:event_close_button_ActionPerformed

    private void log_out_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_button_ActionPerformed
        // Logout and redirect to login page
        int a = JOptionPane.showInternalConfirmDialog(null, "DO YOU REALLY WANT TO LOGOUT", "SELECT", JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login_Page().setVisible(true);
        }    
    }//GEN-LAST:event_log_out_button_ActionPerformed

    private void add_book_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_book_button_ActionPerformed
        // Make Add Book Page Visible
        setVisible(false);
        new Add_Book().setVisible(true);
    }//GEN-LAST:event_add_book_button_ActionPerformed

    private void delete_book_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_book_button_ActionPerformed
        // make Delete Book Visible
        setVisible(false);
        new Delete_Book().setVisible(true);
    }//GEN-LAST:event_delete_book_button_ActionPerformed

    private void issue_book_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_book_button_ActionPerformed
        // Make Issue Book Page Visible
        setVisible(false);
        new Issue_Book().setVisible(true);
    }//GEN-LAST:event_issue_book_button_ActionPerformed

    private void returned_book_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returned_book_button_ActionPerformed
        // Make Returned Book Page Visible
        setVisible(false);
        new Returned_Book().setVisible(true);
    }//GEN-LAST:event_returned_book_button_ActionPerformed

    private void add_student_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_student_button_ActionPerformed
        // Make Returned Book Page Visible
        setVisible(false);
        new Add_Student().setVisible(true);
    }//GEN-LAST:event_add_student_button_ActionPerformed

    private void delete_student_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_student_button_ActionPerformed
        // Make Returned Book Page Visible
        setVisible(false);
        new Delete_Student().setVisible(true);
    }//GEN-LAST:event_delete_student_button_ActionPerformed

    private void edit_student_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_student_button_ActionPerformed
        // Make Returned Book Page Visible
        setVisible(false);
        new Edit_Student().setVisible(true);
    }//GEN-LAST:event_edit_student_button_ActionPerformed

    private void student_fine_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_fine_button_ActionPerformed
        // Make Returned Book Page Visible
        setVisible(false);
        new Student_Fine().setVisible(true);
    }//GEN-LAST:event_student_fine_button_ActionPerformed

    private void search_book_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_book_button_ActionPerformed
        setVisible(false);
        new Search_Book().setVisible(true);
    }//GEN-LAST:event_search_book_button_ActionPerformed

    private void students_list_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_students_list_button_ActionPerformed
        setVisible(false);
        new Students_List().setVisible(true);
    }//GEN-LAST:event_students_list_button_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_book_button_;
    private javax.swing.JButton add_student_button_;
    private javax.swing.JLabel admin_dashboard_label_;
    private javax.swing.JButton close_button_;
    private javax.swing.JButton delete_book_button_;
    private javax.swing.JButton delete_student_button_;
    private javax.swing.JButton edit_student_button_;
    private javax.swing.JButton issue_book_button_;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton log_out_button_;
    private javax.swing.JLabel made_by_blackhatsanta_label_;
    private javax.swing.JLabel powered_by_label_;
    private javax.swing.JButton returned_book_button_;
    private javax.swing.JButton search_book_button_;
    private javax.swing.JButton student_fine_button_;
    private javax.swing.JButton students_list_button_;
    // End of variables declaration//GEN-END:variables
}
