
import classes.ConnectionProvider;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author color
 */
public class Delete_Book extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Delete_Book() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    int found = 0; //We are going to delete book by fetching book_id, so it should not change after fetching data;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book_id_label_ = new javax.swing.JLabel();
        back_button_ = new javax.swing.JButton();
        delete_book_label_ = new javax.swing.JLabel();
        book_id_field_ = new javax.swing.JTextField();
        book_name_label_ = new javax.swing.JLabel();
        book_name_field_ = new javax.swing.JTextField();
        search_book_id_button_ = new javax.swing.JButton();
        book_location_label_ = new javax.swing.JLabel();
        book_location_field_ = new javax.swing.JTextField();
        delete_book_button_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        book_id_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_id_label_.setText("BOOK ID :");

        back_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_button_.setText("BACK");
        back_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_button_ActionPerformed(evt);
            }
        });

        delete_book_label_.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        delete_book_label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete_book_label_.setText("DELETE BOOK");

        book_id_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        book_name_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_name_label_.setText("BOOK NAME :");

        book_name_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        search_book_id_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search_book_id_button_.setText("SEARCH");
        search_book_id_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_book_id_button_ActionPerformed(evt);
            }
        });

        book_location_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_location_label_.setText("BOOK LOCATION :");

        book_location_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_location_field_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_location_field_ActionPerformed(evt);
            }
        });

        delete_book_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete_book_button_.setText("DELETE BOOK");
        delete_book_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_book_button_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(delete_book_label_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(delete_book_button_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back_button_))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(book_name_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book_id_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book_location_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(book_name_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(book_location_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(book_id_field_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 400, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_book_id_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(delete_book_label_)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_id_label_)
                    .addComponent(book_id_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(search_book_id_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_name_label_)
                    .addComponent(book_name_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_location_label_)
                    .addComponent(book_location_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_button_)
                    .addComponent(delete_book_button_))
                .addContainerGap(584, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_button_ActionPerformed
        // Open Admin Page
        setVisible(false);
        new Admin_Home_Page().setVisible(true); 
        
    }//GEN-LAST:event_back_button_ActionPerformed
    String book_id = "";
    private void search_book_id_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_book_id_button_ActionPerformed
        // TODO add your handling code here:
         book_id  = book_id_field_.getText();
           try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet res = st.executeQuery("Select * from books where book_id='"+book_id+"'");
            //book_table_.setModel(DbUtils.resultSetToTableModel(res));
                if(!res.first()) {
                JOptionPane.showInternalConfirmDialog(null, "BOOK ID NOT FOUND ", "SEARCH BOOK",JOptionPane.PLAIN_MESSAGE);
                    setVisible(false);
                    new Delete_Book().setVisible(true);
                } else {
                book_name_field_.setText(res.getString(3));
                book_location_field_.setText(res.getString(8));
                book_location = book_location_field_.getText();
                found = 1;
                }
            } catch(Exception err) {
            JOptionPane.showInternalMessageDialog(null, err);
            }
    }//GEN-LAST:event_search_book_id_button_ActionPerformed
                                                 

    private void book_location_field_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_location_field_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_location_field_ActionPerformed

    String book_location;
    private void delete_book_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_book_button_ActionPerformed
        // TODO add your handling code here:
        if(found==0) 
            JOptionPane.showInternalConfirmDialog(null, "PLEASE ENTER VALID BOOK ID ", "DELETE BOOK",JOptionPane.PLAIN_MESSAGE);
        else if(!book_location.equals("LIBRARY"))
            JOptionPane.showInternalConfirmDialog(null, "BOOK CAN'T BE DELETED AS IT IS NOT AVAILABLE IN THE LIBRARY RIGHT NOW ", "DELETE BOOK",JOptionPane.PLAIN_MESSAGE);

        else {
            try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            st.executeUpdate("delete from books where BOOK_ID='"+book_id+"'");
            int yesOrNo = JOptionPane.showInternalConfirmDialog(null, "DO YOU REALLY WANT TO DELETE THIS BOOK", "DELETE BOOK", JOptionPane.YES_NO_OPTION);
            if(yesOrNo==0) {
                JOptionPane.showInternalConfirmDialog(null, "BOOK DATA DELETED SUCCESSFULLY", "DELETE BOOK",JOptionPane.PLAIN_MESSAGE);
                setVisible(false);
                new Delete_Book().setVisible(true);
            }
                
            } catch(Exception err) {
            JOptionPane.showInternalMessageDialog(null, err);
            }
            
        }   

    }//GEN-LAST:event_delete_book_button_ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button_;
    private javax.swing.JTextField book_id_field_;
    private javax.swing.JLabel book_id_label_;
    private javax.swing.JTextField book_location_field_;
    private javax.swing.JLabel book_location_label_;
    private javax.swing.JTextField book_name_field_;
    private javax.swing.JLabel book_name_label_;
    private javax.swing.JButton delete_book_button_;
    private javax.swing.JLabel delete_book_label_;
    private javax.swing.JButton search_book_id_button_;
    // End of variables declaration//GEN-END:variables

}
