
import classes.ConnectionProvider;
import java.sql.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author color
 */
public class Edit_Student extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Edit_Student() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    int found = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_roll_no_label_ = new javax.swing.JLabel();
        student_name_label_ = new javax.swing.JLabel();
        update_student_button_ = new javax.swing.JButton();
        back_button_ = new javax.swing.JButton();
        dtuName_label_ = new javax.swing.JLabel();
        fathers_name_label_ = new javax.swing.JLabel();
        fathers_name_field_ = new javax.swing.JTextField();
        admission_year_label_ = new javax.swing.JLabel();
        admission_year_field_ = new javax.swing.JTextField();
        branch_label_ = new javax.swing.JLabel();
        student_roll_no_field_ = new javax.swing.JTextField();
        student_name_field_ = new javax.swing.JTextField();
        branch_field_ = new javax.swing.JComboBox<>();
        reset_button_ = new javax.swing.JButton();
        gender_label_ = new javax.swing.JLabel();
        gender_field_ = new javax.swing.JComboBox<>();
        search_student_button_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        student_roll_no_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        student_roll_no_label_.setText("STUDENT ROLL NO.");

        student_name_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        student_name_label_.setText("STUDENT NAME :");

        update_student_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update_student_button_.setText("UPDATE");
        update_student_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_student_button_ActionPerformed(evt);
            }
        });

        back_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_button_.setText("BACK");
        back_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_button_ActionPerformed(evt);
            }
        });

        dtuName_label_.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dtuName_label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dtuName_label_.setText("MODIFY STUDENT RECORD");

        fathers_name_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fathers_name_label_.setText("FATHER'S NAME :");

        fathers_name_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        admission_year_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        admission_year_label_.setText("ADMISSION YEAR :");

        admission_year_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        branch_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        branch_label_.setText("BRANCH :");

        student_roll_no_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        student_name_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        student_name_field_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_name_field_ActionPerformed(evt);
            }
        });

        branch_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        branch_field_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIVIL ", "CHEMICAL", "ELECTRICAL", "MECHANICAL ", "ENVIRONMENT", "BIOTECHNOLOGY", "COMPUTER SCIENCE", "PRODUCTION & INDUSTRIAL", "INFORMATION TECHNOLOGY", "MATHEMATICS & COMPUTATION" }));
        branch_field_.setSelectedItem(branch_field_.getSelectedObjects());
        branch_field_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branch_field_ActionPerformed(evt);
            }
        });

        reset_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset_button_.setText("RESET");
        reset_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_button_ActionPerformed(evt);
            }
        });

        gender_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gender_label_.setText("GENDER :");

        gender_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gender_field_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER" }));

        search_student_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search_student_button_.setText("SEARCH");
        search_student_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_student_button_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtuName_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(student_name_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(400, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(update_student_button_)
                                .addGap(25, 25, 25)
                                .addComponent(reset_button_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(back_button_))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(branch_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(admission_year_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fathers_name_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(student_roll_no_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(gender_label_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(student_name_field_)
                                    .addComponent(fathers_name_field_)
                                    .addComponent(admission_year_field_)
                                    .addComponent(student_roll_no_field_)
                                    .addComponent(branch_field_, javax.swing.GroupLayout.Alignment.TRAILING, 0, 400, Short.MAX_VALUE)
                                    .addComponent(gender_field_, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_student_button_)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(dtuName_label_)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_roll_no_label_)
                    .addComponent(student_roll_no_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(search_student_button_)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_name_label_)
                    .addComponent(student_name_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_label_)
                    .addComponent(gender_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fathers_name_label_)
                    .addComponent(fathers_name_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admission_year_label_)
                    .addComponent(admission_year_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branch_label_)
                    .addComponent(branch_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_button_)
                    .addComponent(update_student_button_)
                    .addComponent(reset_button_))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_student_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_student_button_ActionPerformed
        //Add student and show conformation
        if(found==0) 
            JOptionPane.showInternalConfirmDialog(null, "PLEASE ENTER A VALID ROLL NO", "STUDENT RECORD UPDATE",JOptionPane.PLAIN_MESSAGE);
        else {
            String student_name = student_name_field_.getText();
            String fathers_name = fathers_name_field_.getText();
            String gender = (String)gender_field_.getSelectedItem();
            String admission_year = admission_year_field_.getText();
            String branch = (String)branch_field_.getSelectedItem();
            try{
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                st.executeUpdate("UPDATE students SET STUDENT_NAME = '"+student_name+"', FATHERS_NAME = '"+fathers_name+"' , GENDER ='"+gender+"' , ADMISSION_YEAR =  '"+admission_year+"', BRANCH =  '"+branch+"' where roll_no = '"+roll_no+"' ");
                int yesOrNo = JOptionPane.showInternalConfirmDialog(null, "DO YOU REALLY WANT TO UPDATE THE STUDENT'S RECORD", "UPDATE STUDENT RECORD", JOptionPane.YES_NO_OPTION);
                if(yesOrNo==0) {
                    JOptionPane.showInternalConfirmDialog(null, "STUDENT DATA MODIFIED SUCCESSFULLY", "MODIFY STUDENT RECORD",JOptionPane.PLAIN_MESSAGE);
                    setVisible(false);
                    new Edit_Student().setVisible(true);
                }
                
            } catch(Exception err) {
                JOptionPane.showInternalMessageDialog(null, err);
            }
        
        }
        
    }//GEN-LAST:event_update_student_button_ActionPerformed

    private void back_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_button_ActionPerformed
        // Open Admin Page
        setVisible(false);
        new Admin_Home_Page().setVisible(true); 
        
    }//GEN-LAST:event_back_button_ActionPerformed

    private void branch_field_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branch_field_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branch_field_ActionPerformed

    private void student_name_field_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_name_field_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_name_field_ActionPerformed

    private void reset_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_button_ActionPerformed
        //Clear all fields
        setVisible(false);
        new Edit_Student().setVisible(true);
        
    }//GEN-LAST:event_reset_button_ActionPerformed

    String roll_no = "";
    private void search_student_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_student_button_ActionPerformed
        // TODO add your handling code here:
        roll_no  = student_roll_no_field_.getText();
           try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet res = st.executeQuery("Select * from students where roll_no='"+roll_no+"'");
                if(!res.first()) {
                JOptionPane.showInternalConfirmDialog(null, "STUDENT RECORD NOT FOUND ", "SEARCH STUDENT",JOptionPane.PLAIN_MESSAGE);
                    setVisible(false);
                    new Edit_Student().setVisible(true);
                } else {
                student_name_field_.setText(res.getString(2));
                //gender_field_.setSelectedItem(res.getString(4));
                fathers_name_field_.setText(res.getString(3));
                admission_year_field_.setText(res.getString(5));
                Object obj = res.getString(6);
                //branch_field_.setSelectedItem(obj);
                found = 1;
                }
            } catch(Exception err) {
            JOptionPane.showInternalMessageDialog(null, err);
            }
           
    }//GEN-LAST:event_search_student_button_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admission_year_field_;
    private javax.swing.JLabel admission_year_label_;
    private javax.swing.JButton back_button_;
    private javax.swing.JComboBox<String> branch_field_;
    private javax.swing.JLabel branch_label_;
    private javax.swing.JLabel dtuName_label_;
    private javax.swing.JTextField fathers_name_field_;
    private javax.swing.JLabel fathers_name_label_;
    private javax.swing.JComboBox<String> gender_field_;
    private javax.swing.JLabel gender_label_;
    private javax.swing.JButton reset_button_;
    private javax.swing.JButton search_student_button_;
    private javax.swing.JTextField student_name_field_;
    private javax.swing.JLabel student_name_label_;
    private javax.swing.JTextField student_roll_no_field_;
    private javax.swing.JLabel student_roll_no_label_;
    private javax.swing.JButton update_student_button_;
    // End of variables declaration//GEN-END:variables

}
