
import classes.ConnectionProvider;
import java.sql.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author color
 */
public class Issue_Book extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Issue_Book() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    int found_student = 0;
    int found_book = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_roll_no_label_ = new javax.swing.JLabel();
        issue_book_button_ = new javax.swing.JButton();
        back_button_ = new javax.swing.JButton();
        delete_book_label_ = new javax.swing.JLabel();
        student_roll_no_field_ = new javax.swing.JTextField();
        student_name_label_ = new javax.swing.JLabel();
        student_name_field_ = new javax.swing.JTextField();
        issue_duration_label_ = new javax.swing.JLabel();
        issue_duration_field_ = new javax.swing.JComboBox<>();
        search_student_button_ = new javax.swing.JButton();
        issue_date_label_ = new javax.swing.JLabel();
        issue_date_field_ = new javax.swing.JTextField();
        book_id_label_ = new javax.swing.JLabel();
        book_id_field_ = new javax.swing.JTextField();
        search_book_button_ = new javax.swing.JButton();
        book_title_label_ = new javax.swing.JLabel();
        book_title_field_ = new javax.swing.JTextField();
        book_location_label_ = new javax.swing.JLabel();
        book_location_field_ = new javax.swing.JTextField();
        reset_button_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        student_roll_no_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        student_roll_no_label_.setText("STUDENT ROLL NO :");

        issue_book_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issue_book_button_.setText("ISSUE BOOK");
        issue_book_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue_book_button_ActionPerformed(evt);
            }
        });

        back_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_button_.setText("BACK");
        back_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_button_ActionPerformed(evt);
            }
        });

        delete_book_label_.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        delete_book_label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete_book_label_.setText("ISSUE BOOK");

        student_roll_no_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        student_name_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        student_name_label_.setText("STUDENT NAME :");

        student_name_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        issue_duration_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issue_duration_label_.setText("ISSUING DURATION : ");

        issue_duration_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issue_duration_field_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "15", "30", "60" }));

        search_student_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search_student_button_.setText("SEARCH");
        search_student_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_student_button_ActionPerformed(evt);
            }
        });

        issue_date_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        issue_date_label_.setText("ISSUING DATE :");

        issue_date_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        book_id_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_id_label_.setText("BOOK ID :");

        book_id_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        search_book_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search_book_button_.setText("SEARCH");
        search_book_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_book_button_ActionPerformed(evt);
            }
        });

        book_title_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_title_label_.setText("BOOK TITLE :");

        book_title_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        book_location_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_location_label_.setText("BOOK LOCATION :");

        book_location_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        reset_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset_button_.setText("RESET");
        reset_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_button_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(delete_book_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(400, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(student_roll_no_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(student_roll_no_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(search_student_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(issue_book_button_)
                                .addGap(18, 18, 18)
                                .addComponent(reset_button_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(back_button_))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(student_name_label_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(issue_duration_label_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(issue_date_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(student_name_field_, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(issue_duration_field_, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(issue_date_field_)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(book_id_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(book_id_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(search_book_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(book_title_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(book_title_field_))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(book_location_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(book_location_field_)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(delete_book_label_)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_roll_no_label_)
                    .addComponent(student_roll_no_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_student_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_name_label_)
                    .addComponent(student_name_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_id_label_)
                    .addComponent(book_id_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_book_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_title_label_)
                    .addComponent(book_title_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_location_label_)
                    .addComponent(book_location_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issue_date_label_)
                    .addComponent(issue_date_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issue_duration_label_)
                    .addComponent(issue_duration_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_button_)
                    .addComponent(issue_book_button_)
                    .addComponent(reset_button_))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String book_location;
    private void issue_book_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_book_button_ActionPerformed
        //Add Book and show conformation
        if(found_student==0)
            JOptionPane.showInternalConfirmDialog(null, "PLEASE ENTER A VALID STUDENT ROLL FIRST ", "SEARCH BOOK",JOptionPane.PLAIN_MESSAGE);
        else if(found_book==0)
            JOptionPane.showInternalConfirmDialog(null, "PLEASE ENTER A VALID BOOK ID FIRST ", "SEARCH BOOK",JOptionPane.PLAIN_MESSAGE);
        else if(!book_location.equals("LIBRARY")) {
            JOptionPane.showInternalConfirmDialog(null, "BOOK IS NOT AVAILABLE IN LIBRARY! CAN'T BE ISSUED ", "ISSUE BOOK",JOptionPane.PLAIN_MESSAGE);
        }
        else {
            String student_name = student_name_field_.getText();
            String book_title = book_title_field_.getText();
            String issued_date = issue_date_field_.getText();
            String issue_duration = (String)issue_duration_field_.getSelectedItem();

            
            try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet dueDate = st.executeQuery("select DATE_ADD(CURDATE(), INTERVAL '"+issue_duration+"' DAY);");
                dueDate.next();
                due_date = dueDate.getString(1);
            st.executeUpdate("insert into issued(ROLL_NO, STUDENT_NAME, BOOK_ID, BOOK_TITLE, ISSUED_DATE, DUE_DATE) values('"+roll_no+"' , '"+student_name+"', '"+book_id+"', '"+book_title+"', '"+issued_date+"','"+due_date+"')");
            st.executeUpdate("UPDATE BOOKS SET BOOK_LOCATION = '"+student_name+"' WHERE BOOK_ID = '"+book_id+"' ");
            JOptionPane.showInternalConfirmDialog(null, "BOOK ISSUED SUCCESSFULLY", "ISSUE BOOK",JOptionPane.PLAIN_MESSAGE);
            setVisible(false);
            new Issue_Book().setVisible(true);
            } catch(Exception err) {
            JOptionPane.showInternalMessageDialog(null, err);
            }
        }
            
    }//GEN-LAST:event_issue_book_button_ActionPerformed

    private void back_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_button_ActionPerformed
        // Open Admin Page
        setVisible(false);
        new Admin_Home_Page().setVisible(true); 
        
    }//GEN-LAST:event_back_button_ActionPerformed

    String roll_no = " ";
    String due_date = " ";
    private void search_student_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_student_button_ActionPerformed
        // TODO add your handling code here:
                roll_no  = student_roll_no_field_.getText();
           try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet res = st.executeQuery("Select * from students where roll_no='"+roll_no+"'");
                if(!res.first()) {
                JOptionPane.showInternalConfirmDialog(null, "STUDENT RECORD NOT FOUND ", "SEARCH STUDENT",JOptionPane.PLAIN_MESSAGE);
                } else {
                student_name_field_.setText(res.getString(2));
                found_student = 1;
                }
            } catch(Exception err) {
            JOptionPane.showInternalMessageDialog(null, err);
            }
    }//GEN-LAST:event_search_student_button_ActionPerformed

    String book_id = " ";
    private void search_book_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_book_button_ActionPerformed
        // TODO add your handling code here:
        if(found_student == 0) {
            JOptionPane.showInternalConfirmDialog(null, "PLEASE ENTER STUDENT ROLL NO FIRST ", "SEARCH BOOK",JOptionPane.PLAIN_MESSAGE);

        }
        else {
               book_id  = book_id_field_.getText();
           try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet res = st.executeQuery("Select * from books where book_id='"+book_id+"'");
            //book_table_.setModel(DbUtils.resultSetToTableModel(res));
                if(!res.first()) {
                JOptionPane.showInternalConfirmDialog(null, "BOOK ID NOT FOUND ", "SEARCH BOOK",JOptionPane.PLAIN_MESSAGE);
                } else {
                book_title_field_.setText(res.getString(3));
                book_location_field_.setText(res.getString(8));
                ResultSet issueDate = st.executeQuery("Select CURDATE();");
                issueDate.next();
                issue_date_field_.setText(issueDate.getString(1));
                found_book = 1;
                book_location = book_location_field_.getText();
                }
            } catch(Exception err) {
            JOptionPane.showInternalMessageDialog(null, err);
            }
                
                }

    }//GEN-LAST:event_search_book_button_ActionPerformed

    private void reset_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_button_ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Issue_Book().setVisible(true); 
    }//GEN-LAST:event_reset_button_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button_;
    private javax.swing.JTextField book_id_field_;
    private javax.swing.JLabel book_id_label_;
    private javax.swing.JTextField book_location_field_;
    private javax.swing.JLabel book_location_label_;
    private javax.swing.JTextField book_title_field_;
    private javax.swing.JLabel book_title_label_;
    private javax.swing.JLabel delete_book_label_;
    private javax.swing.JButton issue_book_button_;
    private javax.swing.JTextField issue_date_field_;
    private javax.swing.JLabel issue_date_label_;
    private javax.swing.JComboBox<String> issue_duration_field_;
    private javax.swing.JLabel issue_duration_label_;
    private javax.swing.JButton reset_button_;
    private javax.swing.JButton search_book_button_;
    private javax.swing.JButton search_student_button_;
    private javax.swing.JTextField student_name_field_;
    private javax.swing.JLabel student_name_label_;
    private javax.swing.JTextField student_roll_no_field_;
    private javax.swing.JLabel student_roll_no_label_;
    // End of variables declaration//GEN-END:variables

}
