
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author color
 */
public class Login_Page extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Login_Page() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_label_ = new javax.swing.JLabel();
        password_label_ = new javax.swing.JLabel();
        username_field_ = new javax.swing.JTextField();
        password_field_ = new javax.swing.JPasswordField();
        login_button_ = new javax.swing.JButton();
        close_button_ = new javax.swing.JButton();
        dtuName_label_ = new javax.swing.JLabel();
        libraryApp_label_ = new javax.swing.JLabel();
        forgot_password_button_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        username_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username_label_.setText("USERNAME : ");

        password_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password_label_.setText("PASSWORD : ");

        username_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username_field_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field_ActionPerformed(evt);
            }
        });

        password_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        login_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login_button_.setText("LOGIN");
        login_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_button_ActionPerformed(evt);
            }
        });

        close_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close_button_.setText("CLOSE");
        close_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_button_ActionPerformed(evt);
            }
        });

        dtuName_label_.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dtuName_label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dtuName_label_.setText("DTU");

        libraryApp_label_.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        libraryApp_label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libraryApp_label_.setText("LIBRARY APP");

        forgot_password_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forgot_password_button_.setText("FORGOT PASSWORD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(550, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dtuName_label_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(libraryApp_label_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(username_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password_label_)
                                .addComponent(login_button_))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(close_button_, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(username_field_, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(password_field_))))
                    .addComponent(forgot_password_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(550, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(dtuName_label_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(libraryApp_label_)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_label_)
                    .addComponent(username_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_label_)
                    .addComponent(password_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_button_)
                    .addComponent(close_button_))
                .addGap(42, 42, 42)
                .addComponent(forgot_password_button_)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_field_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field_ActionPerformed

    private void login_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_button_ActionPerformed
        //Show After Login Page
        if(username_field_.getText().equals("") || password_field_.getText().equals("")) {
            JOptionPane.showInternalMessageDialog(null, "USERNAME OR PASSWORD CANNOT BE EMPTY");
        }else if(username_field_.getText().equals("admin") && password_field_.getText().equals("admin")) {
            setVisible(false);                      //Remove Login Page
            new Admin_Home_Page().setVisible(true);       //After Login Show Home Page
        } else {
            JOptionPane.showInternalMessageDialog(null, "INCORRECT USERNAME OR PASSWORD");
        }
    }//GEN-LAST:event_login_button_ActionPerformed

    private void close_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_button_ActionPerformed
        // Close the Program
        int yesOrNo = JOptionPane.showInternalConfirmDialog(null, "DO YOU REALLY WANT TO EXIT", "SELECT", JOptionPane.YES_NO_OPTION);
        if(yesOrNo==0) System.exit(0);        //Close the Program
    }//GEN-LAST:event_close_button_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_button_;
    private javax.swing.JLabel dtuName_label_;
    private javax.swing.JButton forgot_password_button_;
    private javax.swing.JLabel libraryApp_label_;
    private javax.swing.JButton login_button_;
    private javax.swing.JPasswordField password_field_;
    private javax.swing.JLabel password_label_;
    private javax.swing.JTextField username_field_;
    private javax.swing.JLabel username_label_;
    // End of variables declaration//GEN-END:variables

}
