
import classes.ConnectionProvider;
import java.sql.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author color
 */
public class Returned_Book extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Returned_Book() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    int found = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book_id_label_ = new javax.swing.JLabel();
        return_book_button_ = new javax.swing.JButton();
        back_button_ = new javax.swing.JButton();
        delete_book_label_ = new javax.swing.JLabel();
        book_id_field_ = new javax.swing.JTextField();
        student_name_label_ = new javax.swing.JLabel();
        student_name_field_ = new javax.swing.JTextField();
        fine_on_book_label_ = new javax.swing.JLabel();
        search_details_button_ = new javax.swing.JButton();
        due_date_label_ = new javax.swing.JLabel();
        due_date_field_ = new javax.swing.JTextField();
        fine_on_book_field_ = new javax.swing.JTextField();
        book_titile_field_ = new javax.swing.JTextField();
        book_title_label_ = new javax.swing.JLabel();
        roll_no_label_ = new javax.swing.JLabel();
        roll_no_field_ = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        book_id_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_id_label_.setText("BOOK ID :");

        return_book_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        return_book_button_.setText("RETURN BOOK");
        return_book_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_book_button_ActionPerformed(evt);
            }
        });

        back_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_button_.setText("BACK");
        back_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_button_ActionPerformed(evt);
            }
        });

        delete_book_label_.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        delete_book_label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete_book_label_.setText("RETURNED BOOK");

        book_id_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        student_name_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        student_name_label_.setText("STUDENT NAME");

        student_name_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        fine_on_book_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fine_on_book_label_.setText("FINE ON THIS BOOK :");

        search_details_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search_details_button_.setText("SEARCH");
        search_details_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_details_button_ActionPerformed(evt);
            }
        });

        due_date_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        due_date_label_.setText("DUE DATE :");

        due_date_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        fine_on_book_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        book_titile_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        book_title_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        book_title_label_.setText("BOOK TITLE :");

        roll_no_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roll_no_label_.setText("STUDENT ROLL NO :");

        roll_no_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete_book_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(student_name_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(student_name_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(book_id_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(book_id_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(search_details_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fine_on_book_label_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(due_date_label_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(due_date_field_)
                                    .addComponent(fine_on_book_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(return_book_button_)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(back_button_))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(book_title_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(book_titile_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(roll_no_label_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(roll_no_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(delete_book_label_)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_id_label_)
                    .addComponent(book_id_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_details_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_title_label_)
                    .addComponent(book_titile_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roll_no_label_)
                    .addComponent(roll_no_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_name_label_)
                    .addComponent(student_name_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(due_date_label_)
                    .addComponent(due_date_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fine_on_book_label_)
                    .addComponent(fine_on_book_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(return_book_button_)
                    .addComponent(back_button_))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String roll_no = " ";
    String finalFine = " ";
    private void return_book_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_book_button_ActionPerformed
        //Add Book and show conformation
        if(found==0)
        JOptionPane.showInternalConfirmDialog(null, "PLEASE ENTER BOOK ID FIRST", "RETURN BOOK",JOptionPane.PLAIN_MESSAGE);
        else {
            roll_no = roll_no_field_.getText();
            finalFine = fine_on_book_field_.getText();
               
            try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            st.executeUpdate("UPDATE ISSUED SET RETURNED_DATE = '"+return_date+"',STATUS ='RETURNED' WHERE BOOK_ID = '"+book_id+"' ");
            st.executeUpdate("UPDATE BOOKS SET BOOK_LOCATION ='LIBRARY' WHERE BOOK_ID = '"+book_id+"' ");
            st.executeUpdate("UPDATE STUDENTS SET FINE =FINE + '"+finalFine+"'  WHERE ROLL_No = '"+roll_no+"' ");
            JOptionPane.showInternalConfirmDialog(null, "BOOK RETURNED SUCCESSFULLY", "RETURN BOOK",JOptionPane.PLAIN_MESSAGE);
            setVisible(false);
            new Returned_Book().setVisible(true);
            } catch(Exception err) {
            JOptionPane.showInternalMessageDialog(null, err);
            }
        }
    }//GEN-LAST:event_return_book_button_ActionPerformed

    private void back_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_button_ActionPerformed
        // Open Admin Page
        setVisible(false);
        new Admin_Home_Page().setVisible(true); 
        
    }//GEN-LAST:event_back_button_ActionPerformed

    int fine = 0;
    String book_id = " ";
    String return_date = " ";
    private void search_details_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_details_button_ActionPerformed
        // TODO add your handling code here:
                 book_id  = book_id_field_.getText();
           try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet res = st.executeQuery("Select * from issued where book_id='"+book_id+"' AND STATUS = 'ISSUED'");
            //book_table_.setModel(DbUtils.resultSetToTableModel(res));
                if(!res.first()) {
                JOptionPane.showInternalConfirmDialog(null, "BOOK NOT ISSUED TO ANY STUDENT", "SEARCH BOOK",JOptionPane.PLAIN_MESSAGE);
                    setVisible(false);
                    new Returned_Book().setVisible(true);
                } else {
                book_titile_field_.setText(res.getString(5));
                roll_no_field_.setText(res.getString(2));
                student_name_field_.setText(res.getString(3));
                due_date_field_.setText(res.getString(7)); 
                String due_date = (String)res.getString(7);
                
                ResultSet returnDate = st.executeQuery("Select CURDATE();");
                returnDate.next();
                return_date = (String)returnDate.getString(1);
                
                ResultSet fineOnBook = st.executeQuery("select datediff('"+return_date+"', '"+due_date+"');");
                fineOnBook.next();
                String finalFine = (String)fineOnBook.getString(1);
                if(fineOnBook.getInt(1)<0) {
                    finalFine = "0";  
                } 
                fine_on_book_field_.setText(finalFine);
                found = 1;
                }
            } catch(Exception err) {
            JOptionPane.showInternalMessageDialog(null, err);
            }
    }//GEN-LAST:event_search_details_button_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Returned_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button_;
    private javax.swing.JTextField book_id_field_;
    private javax.swing.JLabel book_id_label_;
    private javax.swing.JTextField book_titile_field_;
    private javax.swing.JLabel book_title_label_;
    private javax.swing.JLabel delete_book_label_;
    private javax.swing.JTextField due_date_field_;
    private javax.swing.JLabel due_date_label_;
    private javax.swing.JTextField fine_on_book_field_;
    private javax.swing.JLabel fine_on_book_label_;
    private javax.swing.JButton return_book_button_;
    private javax.swing.JTextField roll_no_field_;
    private javax.swing.JLabel roll_no_label_;
    private javax.swing.JButton search_details_button_;
    private javax.swing.JTextField student_name_field_;
    private javax.swing.JLabel student_name_label_;
    // End of variables declaration//GEN-END:variables

}
