
import classes.ConnectionProvider;
import java.sql.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author color
 */
public class Student_Fine extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Student_Fine() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_rollNo_label_ = new javax.swing.JLabel();
        fine_payNow_button_ = new javax.swing.JButton();
        back_button_ = new javax.swing.JButton();
        delete_book_label_ = new javax.swing.JLabel();
        student_rollNo_field_ = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        student_name_label_ = new javax.swing.JLabel();
        student_name_field_ = new javax.swing.JTextField();
        search_Student_field_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        total_fine_label_ = new javax.swing.JLabel();
        fine_collected_label_ = new javax.swing.JLabel();
        total_fine_field_ = new javax.swing.JTextField();
        fine_collected_field_ = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        student_rollNo_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        student_rollNo_label_.setText("STUDENT ROLL NO. :");

        fine_payNow_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fine_payNow_button_.setText("PAY NOW");
        fine_payNow_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fine_payNow_button_ActionPerformed(evt);
            }
        });

        back_button_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_button_.setText("BACK");
        back_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_button_ActionPerformed(evt);
            }
        });

        delete_book_label_.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        delete_book_label_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete_book_label_.setText("STUDENT FINE");

        student_rollNo_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        student_name_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        student_name_label_.setText("STUDENT NAME :");

        student_name_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        search_Student_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search_Student_field_.setText("SEARCH");
        search_Student_field_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_Student_field_ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("TOP 5 STUDENTS WITH MAX FINE VALUE :");

        total_fine_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total_fine_label_.setText("TOTAL FINE : ");

        fine_collected_label_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fine_collected_label_.setText("FINE COLLECTED : ");

        total_fine_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        fine_collected_field_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete_book_label_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(400, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fine_collected_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(total_fine_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(student_name_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(student_rollNo_label_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(fine_payNow_button_, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(student_rollNo_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(50, 50, 50)
                                            .addComponent(search_Student_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(student_name_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(back_button_))
                                .addComponent(total_fine_field_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fine_collected_field_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(delete_book_label_)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_rollNo_label_)
                    .addComponent(search_Student_field_, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_rollNo_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_name_label_)
                    .addComponent(student_name_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_fine_label_)
                    .addComponent(total_fine_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fine_collected_label_)
                    .addComponent(fine_collected_field_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fine_payNow_button_)
                    .addComponent(back_button_))
                .addContainerGap(385, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fine_payNow_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fine_payNow_button_ActionPerformed
        //Add Book and show conformation
        if(found==0) 
            JOptionPane.showInternalConfirmDialog(null, "PLEASE ENTER A VALID ROLL NO", "PAY NOW",JOptionPane.PLAIN_MESSAGE);
        else {
            String finePaid = fine_collected_field_.getText(); 
            try{
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                st.executeUpdate("UPDATE students SET FINE = '"+totalFine+"'- '"+finePaid+"' where roll_no = '"+roll_no+"' ");
                JOptionPane.showInternalConfirmDialog(null, "PAYMENT SUCCESSFUL", "PAY NOW", JOptionPane.PLAIN_MESSAGE);
                setVisible(false);
                new Student_Fine().setVisible(true);                
            } catch(Exception err) {
                JOptionPane.showInternalMessageDialog(null, err);
            }
        }
    }//GEN-LAST:event_fine_payNow_button_ActionPerformed

    private void back_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_button_ActionPerformed
        // Open Admin Page
        setVisible(false);
        new Student_Fine().setVisible(true); 
        
    }//GEN-LAST:event_back_button_ActionPerformed

    int found;
    String totalFine;
    String roll_no = "";
    private void search_Student_field_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_Student_field_ActionPerformed
        // TODO add your handling code here:
        roll_no  = student_rollNo_field_.getText();
           try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet res = st.executeQuery("Select * from students where roll_no='"+roll_no+"'");
                if(!res.first()) {
                JOptionPane.showInternalConfirmDialog(null, "STUDENT RECORD NOT FOUND ", "SEARCH STUDENT",JOptionPane.PLAIN_MESSAGE);
                    setVisible(false);
                    new Student_Fine().setVisible(true);
                } else {
                totalFine = res.getString("FINE");
                student_name_field_.setText(res.getString("STUDENT_NAME"));
                total_fine_field_.setText(res.getString("FINE"));
                
                found = 1;
                }
            } catch(Exception err) {
            JOptionPane.showInternalMessageDialog(null, err);
            }
    }//GEN-LAST:event_search_Student_field_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Fine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button_;
    private javax.swing.JLabel delete_book_label_;
    private javax.swing.JTextField fine_collected_field_;
    private javax.swing.JLabel fine_collected_label_;
    private javax.swing.JButton fine_payNow_button_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search_Student_field_;
    private javax.swing.JTextField student_name_field_;
    private javax.swing.JLabel student_name_label_;
    private javax.swing.JTextField student_rollNo_field_;
    private javax.swing.JLabel student_rollNo_label_;
    private javax.swing.JTextField total_fine_field_;
    private javax.swing.JLabel total_fine_label_;
    // End of variables declaration//GEN-END:variables

}
